# Configuration Cloud Build pour le déploiement automatique
steps:
  # Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest',
      '.'
    ]

  # Push de l'image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    ]

  # Déploiement sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--service-account', '${_SERVICE_ACCOUNT}',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--set-env-vars', 'SPRING_PROFILES_ACTIVE=${_ENVIRONMENT}',
      '--set-env-vars', 'DB_NAME=${_DB_NAME}',
      '--set-env-vars', 'INSTANCE_CONNECTION_NAME=${_SQL_CONNECTION_NAME}',
      '--set-env-vars', 'DB_USER=${_DB_USER}',
      '--set-secrets', 'DB_PASS=${_DB_PASSWORD_SECRET}:latest',
      '--vpc-connector', '${_VPC_CONNECTOR}',
      '--vpc-egress', 'private-ranges-only'
    ]

  # Tests post-déploiement
  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '-f',
      '--retry', '3',
      '--retry-delay', '10',
      '${_SERVICE_URL}/actuator/health'
    ]

# Variables de substitution
substitutions:
  _REGION: 'europe-west1'
  _REPOSITORY: 'data-centralization-docker'
  _SERVICE_NAME: 'data-centralization-${_ENVIRONMENT}-service'
  _ENVIRONMENT: 'dev'
  _MEMORY: '512Mi'
  _CPU: '1000m'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '5'
  _DB_NAME: 'app_db'
  _DB_USER: 'app_user'
  _SERVICE_ACCOUNT: 'data-centralization-${_ENVIRONMENT}-cloudrun@${PROJECT_ID}.iam.gserviceaccount.com'
  _SQL_CONNECTION_NAME: '${PROJECT_ID}:${_REGION}:data-centralization-${_ENVIRONMENT}-postgres'
  _DB_PASSWORD_SECRET: 'data-centralization-${_ENVIRONMENT}-db-app-password'
  _VPC_CONNECTOR: 'data-centralization-${_ENVIRONMENT}-connector'
  _SERVICE_URL: 'https://data-centralization-${_ENVIRONMENT}-service-${_REGION}-${PROJECT_ID}.a.run.app'

# Configuration des options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout global
timeout: '1200s'

# Tags pour organiser les builds
tags:
  - 'cloud-run'
  - 'data-centralization'
  - '${_ENVIRONMENT}' 